version: '3.5'
services:
  db:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - default
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - default
  flask:
    container_name: gtb-api
    build:
      context: .
      dockerfile: Dockerfile.api
    depends_on:
      - db
    ports:
      - "8085:8085"
    networks:
      - default
  scheduled:
    container_name: gtb-scheduled
    build:
      context: .
      dockerfile: Dockerfile.scheduled
    depends_on:
      - db
    networks:
      - default

networks:
  default:
    name: gtb-net
    driver: bridge
