FROM python:alpine3.15
#COPY app/api /grant-tracking-backend
COPY . /grant-tracking-backend
WORKDIR /grant-tracking-backend
RUN pip install -r app/api/api-requirements.txt
ENV PYTHONPATH "${PYTHONPATH}:/grant-tracking-backend"
EXPOSE 8085
ENTRYPOINT [ "python3" ]
CMD [ "app/api/__init__.py" ]